name: Build and Push Docker Image

# Controls when the action will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to run
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx for cross-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker image tags
      - name: Set up Docker image tags
        id: vars
        run: |
          TAG=${GITHUB_REF##*/}
          if [ "$TAG" == "refs/heads/main" ]; then
            IMAGE_TAG=latest
          else
            IMAGE_TAG=${TAG#refs/tags/}
          fi
          echo "IMAGE_NAME=08050481076/joktan4194:${IMAGE_TAG}"
          echo "IMAGE_NAME_LATEST=08050481076/joktan4194:latest"
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
          echo "IMAGE_NAME_LATEST=${IMAGE_NAME_LATEST}" >> $GITHUB_ENV

      - name: Check Dockerfile
        run: |
            if [ ! -f ./Dockerfile ]; then echo "Dockerfile not found!"; exit 1; fi
        

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME -f ./Dockerfile .

      # Push the Docker image
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME
          if [ "$IMAGE_TAG" == "latest" ]; then
            docker tag $IMAGE_NAME $IMAGE_NAME_LATEST
            docker push $IMAGE_NAME_LATEST
          fi
